create table if not exists public.certificados_portafolio (
    id bigint generated by default as identity primary key,
    nombre text not null,
    emisor text not null,
    categoria text not null default 'Development',
    fecha_emision date,
    nombre_archivo text not null,
    ruta text not null,
    tipo_archivo text,
    orden integer not null default 0,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

alter table public.certificados_portafolio
enable row level security;

drop policy if exists
"Certificados publicos visibles"
on public.certificados_portafolio;

create policy
"Certificados publicos visibles"
on public.certificados_portafolio
for select
to anon, authenticated
using (
    activo = true
    or auth.role() = 'authenticated'
);

drop policy if exists
"Administrador inserta certificados"
on public.certificados_portafolio;

create policy
"Administrador inserta certificados"
on public.certificados_portafolio
for insert
to authenticated
with check (true);

drop policy if exists
"Administrador actualiza certificados"
on public.certificados_portafolio;

create policy
"Administrador actualiza certificados"
on public.certificados_portafolio
for update
to authenticated
using (true)
with check (true);

drop policy if exists
"Administrador elimina certificados"
on public.certificados_portafolio;

create policy
"Administrador elimina certificados"
on public.certificados_portafolio
for delete
to authenticated
using (true);

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'certificados',
    'certificados',
    true,
    10485760,
    array[
        'application/pdf',
        'image/jpeg',
        'image/png',
        'image/webp'
    ]
)
on conflict (id)
do update set
    public = true,
    file_size_limit = 10485760,
    allowed_mime_types = array[
        'application/pdf',
        'image/jpeg',
        'image/png',
        'image/webp'
    ];

drop policy if exists
"Administrador sube certificados"
on storage.objects;

create policy
"Administrador sube certificados"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'certificados'
);

drop policy if exists
"Administrador actualiza archivos certificados"
on storage.objects;

create policy
"Administrador actualiza archivos certificados"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'certificados'
)
with check (
    bucket_id = 'certificados'
);

drop policy if exists
"Administrador elimina archivos certificados"
on storage.objects;

create policy
"Administrador elimina archivos certificados"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'certificados'
);